<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { merchantApi } from '../../api'
import { errorMessage } from '../../api/client'
import StatusTag from '../../components/StatusTag.vue'
import type { PartnerResource } from '../../types'
const items = ref<PartnerResource[]>([]); const loading = ref(false); const dialog = ref(false); const saving = ref(false); const current = ref<PartnerResource | null>(null); const form = reactive({ remaining_capacity: 0, settlement_price: '', status: 'AVAILABLE', reason: '其他渠道已预约' })
async function load() { loading.value = true; try { items.value = (await merchantApi.resources()).data } catch (e) { ElMessage.error(errorMessage(e)) } finally { loading.value = false } }
function open(row: PartnerResource) { current.value = row; form.remaining_capacity = row.remaining_capacity; form.settlement_price = row.settlement_price; form.status = row.status; form.reason = row.remaining_capacity > 0 ? '其他渠道已预约' : '商户暂停资源'; dialog.value = true }
async function save() { if (!current.value) return; saving.value = true; try { const response = await merchantApi.updateResource(current.value.id, { remaining_capacity: form.remaining_capacity, settlement_price: form.settlement_price, status: form.status, reason: form.reason }); ElMessage.success((response.data.message as string) || '更新成功，受影响产品已重算'); dialog.value = false; await load() } catch (e) { ElMessage.error(errorMessage(e)) } finally { saving.value = false } }
onMounted(load)
</script>
<template><div class="page-head"><div><div class="eyebrow">MY CULTURAL RESOURCES</div><h1>我的文旅资源</h1><p>酒店不能直接改商户名额；商户提交后系统会记录事件并更新引用产品。</p></div><div><el-button plain @click="load">刷新</el-button><el-button type="primary" @click="dialog=true;current=null;form.remaining_capacity=0;form.settlement_price='0'">新增资源</el-button></div></div><div class="panel table-wrap"><el-table v-loading="loading" :data="items"><el-table-column prop="resource_name" label="资源名称" min-width="180" /><el-table-column prop="available_date" label="活动日期" width="125" /><el-table-column label="时间" width="150"><template #default="{row}">{{ row.start_time || '--' }} - {{ row.end_time || '--' }}</template></el-table-column><el-table-column label="剩余名额" width="120"><template #default="{row}"><strong :class="row.remaining_capacity <= 5 ? 'warning-text' : ''">{{ row.remaining_capacity }}</strong></template></el-table-column><el-table-column label="结算价" width="100"><template #default="{row}">¥{{ row.settlement_price }}</template></el-table-column><el-table-column label="组包许可" width="110"><template #default="{row}"><StatusTag :status="row.package_enabled ? 'AVAILABLE' : 'UNAVAILABLE'" /></template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><StatusTag :status="row.status" /></template></el-table-column><el-table-column label="引用产品" width="100"><template #default="{row}">{{ row.referenced_product_count }} 个</template></el-table-column><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="primary" @click="open(row)">调整</el-button></template></el-table-column></el-table><div v-if="!loading && !items.length" class="empty-state">暂无资源</div></div><el-dialog v-model="dialog" :title="current ? '实时更新资源' : '新增资源'" width="460px"><el-form label-position="top"><el-form-item label="资源名称" v-if="!current"><el-input placeholder="例如：室内宋韵点茶" /></el-form-item><el-form-item label="剩余名额"><el-input-number v-model="form.remaining_capacity" :min="0" style="width:100%" /></el-form-item><el-form-item label="酒店结算价"><el-input v-model="form.settlement_price"><template #prepend>¥</template></el-input></el-form-item><el-form-item label="资源状态"><el-select v-model="form.status" style="width:100%"><el-option label="可用" value="AVAILABLE" /><el-option label="暂停" value="SUSPENDED" /><el-option label="不可用" value="UNAVAILABLE" /></el-select></el-form-item><el-form-item label="变更原因"><el-input v-model="form.reason" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">提交更新</el-button></template></el-dialog></template>

