<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRouter } from 'vue-router'
import { hotelApi } from '../../api'
import { errorMessage } from '../../api/client'
import StatusTag from '../../components/StatusTag.vue'
import type { TravelProduct } from '../../types'

const router = useRouter(); const items = ref<TravelProduct[]>([]); const loading = ref(false); const status = ref(''); const preview = ref<TravelProduct | null>(null); const previewVisible = ref(false); const marketingLoading = ref(false)
async function load() { loading.value = true; try { items.value = (await hotelApi.products(status.value || undefined)).data.items } catch (e) { ElMessage.error(errorMessage(e)) } finally { loading.value = false } }
async function remove(row: TravelProduct) { try { await ElMessageBox.confirm(`确定删除“${row.product_name}”吗？已有预约意向的产品会安全归档。`, '删除产品', { type: 'warning' }); const response = await hotelApi.deleteProduct(row.id); ElMessage.success(response.data.message); await load() } catch (e) { if (e !== 'cancel' && e !== 'close') ElMessage.error(errorMessage(e)) } }
function poster(row: TravelProduct) { return row.marketing_assets?.find(asset => asset.asset_type === 'POSTER') }
function openPreview(row: TravelProduct) { preview.value = row; previewVisible.value = true }
async function regenerate(row: TravelProduct) { marketingLoading.value = true; try { const updated = (await hotelApi.regenerateMarketing(row.id)).data; const index = items.value.findIndex(item => item.id === row.id); if (index >= 0) items.value[index] = updated; preview.value = updated; ElMessage.success('已按当前套餐资源重新生成营销素材') } catch (e) { ElMessage.error(errorMessage(e)) } finally { marketingLoading.value = false } }
onMounted(load)
</script>

<template>
  <div class="page-head"><div><div class="eyebrow">PRODUCT POOL</div><h1>当前产品池</h1><p>统一查看套餐库存、经营数字和营销素材；每个产品都可以打开具体的场景图、社交文案、短视频分镜和售卖卡。</p></div><div><el-button plain @click="load">刷新</el-button><el-button type="primary" @click="router.push('/hotel/products/generate')">＋ 生成新方案</el-button></div></div>
  <div class="panel filter-bar"><el-radio-group v-model="status" @change="load"><el-radio-button label="">全部</el-radio-button><el-radio-button label="DRAFT">草稿</el-radio-button><el-radio-button label="ON_SALE">在售</el-radio-button><el-radio-button label="LOW_STOCK">库存紧张</el-radio-button><el-radio-button label="PAUSED">已暂停</el-radio-button></el-radio-group></div>
  <div class="product-pool-grid"><article v-for="row in items" :key="row.id" class="pool-card panel"><div class="pool-card__visual" @click="openPreview(row)"><div v-if="poster(row)?.poster_svg" v-html="poster(row)?.poster_svg" /><div v-else class="pool-card__placeholder"><span>STAYSCAPE</span><strong>{{ row.marketing_title }}</strong></div><span class="visual-hint">查看营销素材</span></div><div class="pool-card__body"><div class="product-card__top"><span class="eyebrow">{{ row.theme }} · {{ row.target_date }}</span><StatusTag :status="row.status" /></div><h2>{{ row.product_name }}</h2><p class="pool-card__copy">{{ row.marketing_content }}</p><div class="product-card__resources"><span v-for="resource in row.resources.slice(0, 4)" :key="resource.id">{{ resource.resource_name }}</span></div><div class="pool-card__metrics"><div><small>可售</small><strong>{{ row.sale_quantity }} 套</strong></div><div><small>售价</small><strong>¥{{ row.suggested_price }}</strong></div><div><small>毛利率</small><strong>{{ (Number(row.gross_margin) * 100).toFixed(1) }}%</strong></div></div><div class="pool-card__actions"><el-button plain @click="openPreview(row)">营销预览</el-button><el-button link type="primary" @click="router.push(`/hotel/products/${row.id}`)">详情 / 编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></div></div></article></div><div v-if="!loading && !items.length" class="panel empty-state">暂无符合条件的产品，先生成一组真实库存驱动的主题方案。</div>

  <el-dialog v-if="preview" v-model="previewVisible" title="文旅营销素材工作台" width="980px" top="4vh"><div class="marketing-workbench"><div class="workbench-poster"><div v-if="poster(preview)?.poster_svg" v-html="poster(preview)?.poster_svg" /><div class="poster-caption">{{ preview.product_name }} · {{ preview.target_date }} · {{ preview.weather }}</div></div><div class="workbench-copy"><div class="workbench-title"><div><div class="eyebrow">CONTENT KIT</div><h2>{{ preview.marketing_title }}</h2></div><el-button type="primary" plain :loading="marketingLoading" @click="regenerate(preview)">重新生成</el-button></div><div v-for="asset in preview.marketing_assets.filter(item => item.asset_type !== 'POSTER')" :key="asset.asset_type" class="copy-card"><div class="product-card__top"><strong>{{ asset.title }}</strong><el-tag size="small" effect="plain">{{ asset.platform }}</el-tag></div><p>{{ asset.content }}</p><small>{{ asset.visual_brief }}</small><b>{{ asset.call_to_action }}</b></div></div></div><template #footer><el-button @click="router.push(`/hotel/products/${preview.id}`)">进入产品详情</el-button><el-button type="primary" @click="previewVisible = false">关闭</el-button></template></el-dialog>
</template>

<style scoped>
.filter-bar{margin-bottom:18px}.filter-bar :deep(.el-radio-group){display:flex;flex-wrap:wrap;gap:8px}.filter-bar :deep(.el-radio-button__inner){border-left:1px solid var(--line);border-radius:999px!important;box-shadow:none!important}.product-pool-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.pool-card{padding:0;overflow:hidden}.pool-card__visual{height:270px;position:relative;background:#e7f1ed;overflow:hidden;cursor:pointer}.pool-card__visual :deep(svg){width:100%;height:100%;object-fit:cover;display:block}.visual-hint{position:absolute;right:14px;bottom:14px;padding:7px 10px;border-radius:999px;background:rgba(16,61,56,.84);color:#fff;font-size:11px}.pool-card__placeholder{height:100%;display:grid;place-items:center;align-content:center;gap:12px;color:var(--teal);padding:20px;text-align:center}.pool-card__placeholder span{letter-spacing:3px;font-size:11px}.pool-card__placeholder strong{font-size:20px}.pool-card__body{padding:20px}.pool-card__body h2{margin:12px 0 8px;font-size:20px}.pool-card__copy{min-height:48px;color:var(--muted);font-size:13px;line-height:1.75;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.pool-card__metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:15px 0}.pool-card__metrics div{padding:11px 12px;background:#f7fbf9;border-radius:10px}.pool-card__metrics small,.pool-card__metrics strong{display:block}.pool-card__metrics small{color:var(--muted);font-size:11px}.pool-card__metrics strong{margin-top:5px;color:var(--teal-dark);font-size:16px}.pool-card__actions{display:flex;align-items:center;gap:5px;flex-wrap:wrap}.marketing-workbench{display:grid;grid-template-columns:minmax(280px,.8fr) minmax(0,1.2fr);gap:20px}.workbench-poster{border-radius:16px;overflow:hidden;background:#e7f1ed;align-self:start}.workbench-poster :deep(svg){width:100%;display:block}.poster-caption{padding:10px 12px;background:#174d46;color:#e4f4ee;font-size:12px}.workbench-copy{min-width:0}.workbench-title{display:flex;justify-content:space-between;gap:12px;align-items:start;margin-bottom:12px}.workbench-title h2{font-size:21px;margin:7px 0 0}.copy-card{padding:14px;border:1px solid var(--line);border-radius:12px;background:#fbfdfc;margin-top:10px}.copy-card p{white-space:pre-wrap;line-height:1.75;font-size:13px;margin:10px 0}.copy-card small{display:block;color:var(--muted);line-height:1.6}.copy-card b{display:block;color:var(--teal);font-size:12px;margin-top:8px}@media(max-width:850px){.product-pool-grid,.marketing-workbench{grid-template-columns:1fr}}
</style>
