<script setup lang="ts">
import { posterSvgDataUri } from '../../utils/posterSvg'
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRouter } from 'vue-router'
import { hotelApi } from '../../api'
import { errorMessage } from '../../api/client'
import StatusTag from '../../components/StatusTag.vue'
import DateHeatmap from '../../components/DateHeatmap.vue'
import type { TravelProduct } from '../../types'

const router = useRouter(); const items = ref<TravelProduct[]>([]); const loading = ref(false); const status = ref(''); const selectedDate = ref(''); const viewMode = ref<'cards' | 'list'>('cards'); const preview = ref<TravelProduct | null>(null); const previewVisible = ref(false); const marketingLoading = ref(false)
const visibleItems = computed(() => selectedDate.value ? items.value.filter((item) => item.target_date === selectedDate.value) : items.value)
async function load() { loading.value = true; try { items.value = (await hotelApi.products(status.value || undefined)).data.items } catch (e) { ElMessage.error(errorMessage(e)) } finally { loading.value = false } }
async function remove(row: TravelProduct) { try { await ElMessageBox.confirm(`确定删除“${row.product_name}”吗？已有预约意向的产品会安全归档。`, '删除产品', { type: 'warning' }); const response = await hotelApi.deleteProduct(row.id); ElMessage.success(response.data.message); await load() } catch (e) { if (e !== 'cancel' && e !== 'close') ElMessage.error(errorMessage(e)) } }
function poster(row: TravelProduct) { return row.marketing_assets?.find(asset => asset.asset_type === 'POSTER') }
function openPreview(row: TravelProduct) { preview.value = row; previewVisible.value = true }
async function regenerate(row: TravelProduct) { marketingLoading.value = true; try { const updated = (await hotelApi.regenerateMarketing(row.id, { style: 'SEEDING', generate_image: true })).data; const index = items.value.findIndex(item => item.id === row.id); if (index >= 0) items.value[index] = updated; preview.value = updated; ElMessage.success('已生成新的旅行者文案、SVG 海报与产品专属主图') } catch (e) { ElMessage.error(errorMessage(e)) } finally { marketingLoading.value = false } }
onMounted(load)
</script>

<template>
  <div class="page-head"><div><div class="eyebrow">产品池</div><h1>当前产品池</h1><p>按日期查看待发布、在售和库存紧张的产品；可在详情中编辑内容与生成宣传素材。</p></div><div class="header-actions"><el-radio-group v-model="viewMode" class="view-mode-switch" size="small" aria-label="产品展示方式"><el-radio-button label="cards">卡片</el-radio-button><el-radio-button label="list">列表</el-radio-button></el-radio-group><el-button plain @click="load">刷新</el-button><el-button type="primary" @click="router.push('/hotel/products/generate')">＋ 生成新方案</el-button></div></div>
  <div class="panel filter-bar"><div><el-radio-group v-model="status" @change="load"><el-radio-button label="">全部</el-radio-button><el-radio-button label="DRAFT">草稿</el-radio-button><el-radio-button label="ON_SALE">在售</el-radio-button><el-radio-button label="LOW_STOCK">库存紧张</el-radio-button><el-radio-button label="PAUSED">已暂停</el-radio-button></el-radio-group><DateHeatmap v-model="selectedDate" :items="items" date-key="target_date" quantity-key="sale_quantity" label="出发日期" /></div></div>
  <div v-if="viewMode === 'cards'" class="product-pool-grid"><article v-for="row in visibleItems" :key="row.id" class="pool-card panel"><div class="pool-card__visual" @click="openPreview(row)"><img v-if="poster(row)?.poster_svg" :src="posterSvgDataUri(poster(row)?.poster_svg)" :alt="poster(row)?.title || row.product_name" /><img v-else-if="poster(row)?.image_url" :src="poster(row)?.image_url" :alt="poster(row)?.title || row.product_name" /><div v-else class="pool-card__placeholder"><span>杭州旅居</span><strong>{{ row.marketing_title }}</strong></div><span class="visual-hint">查看宣传素材</span></div><div class="pool-card__body"><div class="product-card__top"><span class="eyebrow">{{ row.theme }} · {{ row.target_date }}</span><StatusTag :status="row.status" /></div><h2>{{ row.product_name }}</h2><p class="pool-card__copy">{{ row.marketing_content }}</p><div class="product-card__resources"><span v-for="resource in row.resources.slice(0, 3)" :key="resource.id">{{ resource.resource_name }}</span></div><div class="pool-card__metrics"><div><small>可售</small><strong>{{ row.sale_quantity }} 套</strong></div><div><small>售价</small><strong>¥{{ row.suggested_price }}</strong></div><div><small>毛利率</small><strong>{{ (Number(row.gross_margin) * 100).toFixed(1) }}%</strong></div></div><div class="pool-card__actions"><el-button plain @click="openPreview(row)">素材预览</el-button><el-button link type="primary" @click="router.push(`/hotel/products/${row.id}`)">详情</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></div></div></article></div>
  <div v-else class="panel table-wrap"><el-table v-loading="loading" :data="visibleItems" style="width:100%" @row-click="openPreview"><el-table-column prop="product_name" label="产品" min-width="250"><template #default="{row}"><strong>{{ row.product_name }}</strong><div class="muted">{{ row.theme }} · {{ row.target_date }}</div></template></el-table-column><el-table-column label="状态" width="105"><template #default="{row}"><StatusTag :status="row.status" /></template></el-table-column><el-table-column label="可售" width="85"><template #default="{row}">{{ row.sale_quantity }} 套</template></el-table-column><el-table-column label="售价" width="100"><template #default="{row}">¥{{ row.suggested_price }}</template></el-table-column><el-table-column label="素材" width="100"><template #default="{row}"><span :class="poster(row)?.image_url ? 'success-text' : 'muted'">{{ poster(row)?.image_url ? 'AI 主图' : 'SVG 海报' }}</span></template></el-table-column><el-table-column label="操作" width="150"><template #default="{row}"><el-button link type="primary" @click.stop="openPreview(row)">预览</el-button><el-button link type="primary" @click.stop="router.push(`/hotel/products/${row.id}`)">编辑</el-button><el-button link type="danger" @click.stop="remove(row)">删除</el-button></template></el-table-column></el-table></div>
  <div v-if="!loading && !visibleItems.length" class="panel empty-state">这一天暂无产品；可切换日期，或生成一组新方案。</div>

  <el-dialog v-if="preview" v-model="previewVisible" title="宣传素材工作台" width="980px" top="4vh"><div class="marketing-workbench"><div class="workbench-poster"><img v-if="poster(preview)?.poster_svg" :src="posterSvgDataUri(poster(preview)?.poster_svg)" :alt="poster(preview)?.title || preview.product_name" /><img v-else-if="poster(preview)?.image_url" :src="poster(preview)?.image_url" :alt="poster(preview)?.title || preview.product_name" /><div class="poster-caption">{{ preview.product_name }} · {{ preview.target_date }} · {{ preview.weather }}</div></div><div class="workbench-copy"><div class="workbench-title"><div><div class="eyebrow">宣传内容</div><h2>{{ preview.marketing_title }}</h2></div><el-button type="primary" plain :loading="marketingLoading" @click="regenerate(preview)">生成主图与文案</el-button></div><div v-for="asset in preview.marketing_assets.filter(item => item.asset_type !== 'POSTER')" :key="asset.asset_type" class="copy-card"><div class="product-card__top"><strong>{{ asset.title }}</strong><el-tag size="small" effect="plain">{{ asset.platform }}</el-tag></div><p>{{ asset.content }}</p><small>{{ asset.visual_brief }}</small><b>{{ asset.call_to_action }}</b></div></div></div><template #footer><el-button @click="router.push(`/hotel/products/${preview.id}`)">进入产品详情</el-button><el-button type="primary" @click="previewVisible = false">关闭</el-button></template></el-dialog>
</template>

<style scoped>
.filter-bar{margin-bottom:18px}.filter-bar :deep(.el-radio-group){display:flex;flex-wrap:wrap;gap:8px}.filter-bar :deep(.el-radio-button__inner){border-left:1px solid var(--line);border-radius:999px!important;box-shadow:none!important}.product-pool-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.pool-card{padding:0;overflow:hidden}.pool-card__visual{height:270px;position:relative;background:#e7f1ed;overflow:hidden;cursor:pointer}.pool-card__visual :deep(svg){width:100%;height:100%;object-fit:cover;display:block}.visual-hint{position:absolute;right:14px;bottom:14px;padding:7px 10px;border-radius:999px;background:rgba(16,61,56,.84);color:#fff;font-size:11px}.pool-card__placeholder{height:100%;display:grid;place-items:center;align-content:center;gap:12px;color:var(--teal);padding:20px;text-align:center}.pool-card__placeholder span{letter-spacing:3px;font-size:11px}.pool-card__placeholder strong{font-size:20px}.pool-card__body{padding:20px}.pool-card__body h2{margin:12px 0 8px;font-size:20px}.pool-card__copy{min-height:48px;color:var(--muted);font-size:13px;line-height:1.75;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.pool-card__metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:15px 0}.pool-card__metrics div{padding:11px 12px;background:#f7fbf9;border-radius:10px}.pool-card__metrics small,.pool-card__metrics strong{display:block}.pool-card__metrics small{color:var(--muted);font-size:11px}.pool-card__metrics strong{margin-top:5px;color:var(--teal-dark);font-size:16px}.pool-card__actions{display:flex;align-items:center;gap:5px;flex-wrap:wrap}.marketing-workbench{display:grid;grid-template-columns:minmax(280px,.8fr) minmax(0,1.2fr);gap:20px}.workbench-poster{border-radius:16px;overflow:hidden;background:#e7f1ed;align-self:start}.workbench-poster :deep(svg){width:100%;display:block}.poster-caption{padding:10px 12px;background:#174d46;color:#e4f4ee;font-size:12px}.workbench-copy{min-width:0}.workbench-title{display:flex;justify-content:space-between;gap:12px;align-items:start;margin-bottom:12px}.workbench-title h2{font-size:21px;margin:7px 0 0}.copy-card{padding:14px;border:1px solid var(--line);border-radius:12px;background:#fbfdfc;margin-top:10px}.copy-card p{white-space:pre-wrap;line-height:1.75;font-size:13px;margin:10px 0}.copy-card small{display:block;color:var(--muted);line-height:1.6}.copy-card b{display:block;color:var(--teal);font-size:12px;margin-top:8px}@media(max-width:850px){.product-pool-grid,.marketing-workbench{grid-template-columns:1fr}}

/* Stable SVG image rendering */
.pool-card__visual>img,.workbench-poster>img{display:block;width:100%;height:100%;object-fit:cover;background:#e7f1ed}
.workbench-poster>img{height:auto}.pool-card__body{padding:18px}.pool-card__copy{font-size:14px;line-height:1.7}
.filter-bar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.product-pool-grid{grid-template-columns:repeat(auto-fill,minmax(245px,1fr));gap:12px}.pool-card__visual{height:150px}.pool-card__body{padding:13px}.pool-card__body h2{overflow:hidden;margin:9px 0 6px;font-size:16px;text-overflow:ellipsis;white-space:nowrap}.pool-card__copy{min-height:38px;font-size:11px;line-height:1.55}.pool-card__metrics{gap:5px;margin:11px 0}.pool-card__metrics div{padding:8px;background:var(--panel-soft);border-radius:8px}.pool-card__metrics small{font-size:9px}.pool-card__metrics strong{font-family:var(--font-mono);font-size:12px}.visual-hint{right:10px;bottom:10px;padding:5px 8px;font-size:10px}.success-text{color:#40665b;font-size:11px;font-weight:600}@media(max-width:700px){.filter-bar{align-items:stretch;flex-direction:column}.product-pool-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.pool-card__visual{height:105px}.pool-card__body{padding:10px}.pool-card__metrics{grid-template-columns:1fr 1fr}.pool-card__metrics div:last-child{display:none}}

/* The image is a thumbnail, not a background for operational information. */
.header-actions{display:flex;align-items:center;justify-content:flex-end;gap:10px;flex-wrap:wrap}.view-mode-switch{order:-1}.filter-bar{display:block;padding:10px 12px}.filter-bar>div{display:grid;gap:9px}.filter-bar :deep(.date-heatmap){border:0;padding:0;background:transparent}.product-pool-grid{grid-template-columns:repeat(auto-fill,minmax(390px,1fr));gap:10px}.pool-card{display:grid;grid-template-columns:124px minmax(0,1fr);min-height:176px}.pool-card__visual{height:auto;min-height:176px}.pool-card__visual>img{height:100%;object-fit:cover}.pool-card__body{min-width:0;padding:12px}.pool-card__body h2{margin:7px 0 4px;font-size:15px}.pool-card__copy{min-height:32px;margin:0;font-size:11px;line-height:1.48}.pool-card .product-card__resources{max-height:43px;margin:8px 0;overflow:hidden}.pool-card .product-card__resources span{font-size:9px}.pool-card__metrics{margin:8px 0;gap:5px}.pool-card__metrics div{padding:6px 7px}.pool-card__metrics strong{font-size:11px}.visual-hint{right:7px;bottom:7px;padding:4px 6px;background:rgba(31,34,32,.78);font-size:9px}.pool-card__actions{gap:3px}.pool-card__actions :deep(.el-button){min-height:27px;padding:5px 7px;font-size:10px}@media(max-width:700px){.page-head .header-actions{justify-content:flex-start;margin-top:12px}.filter-bar{padding:10px}.product-pool-grid{grid-template-columns:1fr}.pool-card{grid-template-columns:100px minmax(0,1fr);min-height:142px}.pool-card__visual{min-height:142px}.pool-card__body{padding:10px}.pool-card__metrics{margin:7px 0}.pool-card__metrics div{padding:5px}.pool-card__metrics div:last-child{display:block}.pool-card .product-card__resources{display:none}}
</style>
