<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { hotelApi } from '../../api'
import { errorMessage } from '../../api/client'
import StatusTag from '../../components/StatusTag.vue'
import type { Adjustment, TravelProduct } from '../../types'
const route = useRoute(); const product = ref<TravelProduct | null>(null); const adjustments = ref<Adjustment[]>([]); const loading = ref(true)
async function load() { try { const response = await hotelApi.product(Number(route.params.id)); product.value = response.data; adjustments.value = (response.data as TravelProduct & { adjustments?: Adjustment[] }).adjustments || [] } catch (e) { ElMessage.error(errorMessage(e)) } finally { loading.value = false } }
async function setStatus(status: string) { if (!product.value) return; try { product.value = (await hotelApi.productStatus(product.value.id, status)).data; ElMessage.success('产品状态已更新') } catch (e) { ElMessage.error(errorMessage(e)) } }
onMounted(load)
</script>

<template>
  <div v-loading="loading"><div v-if="product"><div class="page-head"><div><div class="eyebrow">PRODUCT DETAIL · {{ product.product_code }}</div><h1>{{ product.product_name }}</h1><p>{{ product.target_date }} · {{ product.theme }} · {{ product.target_crowd }}</p></div><div><StatusTag :status="product.status" /><el-button v-if="product.status === 'DRAFT'" type="primary" style="margin-left:10px" @click="setStatus('ON_SALE')">模拟发布</el-button><el-button v-if="['ON_SALE','LOW_STOCK'].includes(product.status)" plain @click="setStatus('PAUSED')">暂停销售</el-button></div></div><div class="metric-grid"><div class="metric-card"><div class="metric-label">可售数量</div><div class="metric-value">{{ product.sale_quantity }} 套</div><div class="metric-hint">瓶颈：{{ product.bottleneck_resource }}</div></div><div class="metric-card"><div class="metric-label">单套成本</div><div class="metric-value">¥{{ product.unit_cost }}</div><div class="metric-hint">房间、服务、合作资源成本合计</div></div><div class="metric-card"><div class="metric-label">建议售价</div><div class="metric-value">¥{{ product.suggested_price }}</div><div class="metric-hint">最低允许 ¥{{ product.minimum_allowed_price }}</div></div><div class="metric-card"><div class="metric-label">单套毛利</div><div class="metric-value">¥{{ product.gross_profit }}</div><div class="metric-hint">毛利率 {{ (Number(product.gross_margin) * 100).toFixed(2) }}%</div></div></div><div class="detail-grid"><div><div class="panel"><div class="section-title" style="margin-top:0"><h2>资源组成</h2><span>确定性校验后的最终组合</span></div><table class="data-table"><thead><tr><th>资源</th><th>类型</th><th>每套消耗</th><th>单位成本</th></tr></thead><tbody><tr v-for="item in product.resources" :key="item.id"><td><strong>{{ item.resource_name }}</strong></td><td class="muted">{{ item.resource_type }}</td><td>{{ item.quantity_per_package }}</td><td>¥{{ item.unit_cost }}</td></tr></tbody></table></div><div class="panel" style="margin-top:18px"><div class="section-title" style="margin-top:0"><h2>营销内容</h2></div><h3>{{ product.marketing_title }}</h3><p class="muted" style="line-height:1.8">{{ product.marketing_content }}</p><p class="danger-text" style="line-height:1.7">{{ product.risk_message }}</p></div></div><div class="panel"><div class="section-title" style="margin-top:0"><h2>动态调整</h2><span>{{ adjustments.length }} 条</span></div><div v-if="!adjustments.length" class="empty-state">发布后资源变化会出现在这里</div><div v-for="item in adjustments" :key="item.id" style="padding:13px 0;border-top:1px solid var(--line)"><div style="display:flex;justify-content:space-between"><strong>{{ item.old_quantity }} → {{ item.new_quantity }} 套</strong><span class="muted">{{ item.action }}</span></div><p class="muted" style="line-height:1.6">{{ item.reason }}</p></div></div></div></div><div v-else-if="!loading" class="panel empty-state">产品不存在或已被删除</div></div>
</template>

