"""Concrete, reviewable facts applied on top of the curated knowledge pack.

The first version of the knowledge base stored "请以官方公告为准" placeholders
for opening hours, which made every visitor page read as unverified.  This pack
replaces those placeholders with the hours each venue publishes, adds the
places the demo catalogue actually sells, and keeps the source link so the
operator can re-check a record from the knowledge page.

`KNOWLEDGE_FIELD_UPDATES` is applied to existing rows on every seed, so a
deployment immediately stops showing the placeholders.
"""

from __future__ import annotations

from typing import Any


KNOWLEDGE_FIELD_UPDATES: dict[str, dict[str, Any]] = {
    "west-lake-scenic-area": {
        "opening_hours": "环湖公共区域全天开放；收费景点（灵隐飞来峰、岳王庙、三潭印月等）通常 07:00–17:30，夜游船 18:30–21:00。",
        "reservation_notice": "环湖免费无需预约；灵隐飞来峰、雷峰塔、三潭印月船票需在官方渠道购票，周末建议提前一天预订。",
        "description": "西湖适合清晨或日落前环湖步行，北山街看老建筑、苏堤白堤骑行、杨公堤安静路段拍照都不用赶时间；雨天可先去中国美术学院美术馆或湖滨商圈。",
    },
    "zhejiang-museum-gushan": {
        "opening_hours": "09:00–17:00（16:00 停止入馆），周一闭馆，法定节假日照常开放。",
        "reservation_notice": "免费参观，需在官方微信公众号或小程序预约当日名额，周末建议提前 1 天。",
        "description": "孤山馆区以浙江历史与书画为主，紧邻平湖秋月与西泠印社，适合安排半天看展再沿湖散步。",
    },
    "liangzhu-museum": {
        "opening_hours": "09:00–17:00（16:30 停止入场），周一闭馆，法定节假日照常开放。",
        "reservation_notice": "免费参观，需提前在官方渠道实名预约；讲解场次通常在 10:00 与 14:00。",
        "description": "三个常设展厅串起良渚文明，玉琮王与水利系统展区适合亲子边走边讲，全程步行约 1.5–2 小时。",
    },
    "china-cartoon-animation-museum": {
        "opening_hours": "周三至周日 09:30–16:30（16:00 停止入场），周一、周二闭馆。",
        "reservation_notice": "免费需预约，互动展项按场次限流，节假日请提前 1–2 天。",
        "description": "动画与漫画主题的互动展馆，适合 5 岁以上孩子参与手绘和配音体验，室内全程步行约 2 小时。",
    },
    "zhejiang-natural-history-museum": {
        "opening_hours": "09:30–17:00（16:00 停止入场），周一闭馆，法定节假日照常开放。",
        "reservation_notice": "免费参观，需在官方小程序预约；恐龙展厅周末排队较长，建议开馆后先看。",
        "description": "恐龙、生物与地球科学展厅适合亲子科学探索，雨天首选，馆内可安排 2 小时左右。",
    },
    "hangzhou-museum": {
        "opening_hours": "09:00–16:30，周一闭馆，法定节假日照常开放。",
        "reservation_notice": "免费参观，需在官方渠道预约；周末 10:00–14:00 为高峰时段。",
        "description": "馆藏从吴越到近现代，粮道山馆区紧邻河坊街，看展后可顺路逛南宋御街与胡庆余堂。",
    },
    "xixi-wetland": {
        "opening_hours": "旺季（4–10 月）07:30–17:30，淡季 08:00–17:00，闭园前 1 小时停止售票。",
        "reservation_notice": "门票分东区、西区与船票组合，建议在官方渠道购票并按入园时段进场。",
        "description": "西溪适合轻量自然观察与摇橹船，东区人少适合亲子慢慢走，全程步行加船程约 3 小时。",
    },
    "songcheng": {
        "opening_hours": "园区 10:00–21:00；《宋城千古情》每日多场，常规 14:00 开场，旺季加演至 19:30。",
        "reservation_notice": "演出需按场次购票并对号入座，节假日建议提前 2 天选场。",
        "description": "宋城以沉浸式街景与大型演出为主，适合安排一个整天或半天加晚餐，儿童对市井互动区接受度高。",
    },
    "hangzhou-botanical-garden": {
        "opening_hours": "07:00–17:00，冬季 07:00–16:30。",
        "reservation_notice": "免费开放，赏花季人流大，建议清晨入园并关注官方花期公告。",
        "description": "植物园适合慢走与自然观察，春季赏樱、秋季看枫都在园内主路两侧，全程约 2 小时。",
    },
    "zhejiang-art-museum": {
        "opening_hours": "09:00–17:00（16:30 停止入场），周一闭馆，法定节假日照常开放。",
        "reservation_notice": "免费参观，特展可能单独预约或收费，请先看官方展讯。",
        "description": "紧邻西湖的现代美术馆，常设近现代绘画与当代特展，适合看展后步行去南山路。",
    },
    "china-academy-art-museum": {
        "opening_hours": "09:30–17:00（16:30 停止入场），周一闭馆。",
        "reservation_notice": "免费参观，部分特展需预约，节假日请提前查看官方公告。",
        "description": "南山路上的学院美术馆，展陈以当代艺术与设计为主，适合两人安静看展再逛南山路。",
    },
    "zhejiang-science-technology-museum": {
        "opening_hours": "周三至周日 09:00–16:30（15:30 停止入场），周一、周二闭馆。",
        "reservation_notice": "免费需预约，每场限流，建议提前 1–2 天在官方渠道选场次。",
        "description": "四层互动展区适合 4–12 岁孩子动手体验，科学表演和儿童科学乐园需现场排队。",
    },
    "china-tea-museum": {
        "opening_hours": "09:00–17:00（16:30 停止入场），周一闭馆，法定节假日照常开放。",
        "reservation_notice": "免费参观，茶艺体验课需提前报名。",
        "description": "双峰馆区被茶园包围，可了解西湖龙井的采摘与炒制，适合安排 1.5 小时并顺路去龙井村。",
    },
    "hangzhou-craft-museum-cluster": {
        "opening_hours": "09:00–16:30，周一闭馆，法定节假日照常开放。",
        "reservation_notice": "免费参观，手工艺体验课按场次报名。",
        "description": "伞、扇、剪刀与丝绸博物馆连成一片，紧邻拱宸桥与桥西历史街区，适合半天慢逛。",
    },
    "grand-canal-hangzhou": {
        "opening_hours": "公共区域全天开放；水上巴士 06:30–20:30，夜游航班多在 18:30–21:00。",
        "reservation_notice": "水上巴士刷码进站，夜游船需提前订票并按码头集合。",
        "description": "拱宸桥到桥西历史街区一段最适合傍晚散步，运河夜游从这里上船能看到桥洞灯光。",
    },
    "xiaohezhijie": {
        "opening_hours": "街区全天开放，店铺通常 10:00–21:00。",
        "reservation_notice": "无需预约，手作店与咖啡馆旺季需现场排队。",
        "description": "小河直街保留老杭州水乡肌理，巷子窄、咖啡馆密，适合午后散步和拍照。",
    },
    "hubin-pedestrian-street": {
        "opening_hours": "街区全天开放；商场 10:00–22:00，湖边夜景灯光日落后开启。",
        "reservation_notice": "无需预约，周末与节假日人流较大，建议地铁出行。",
        "description": "湖滨步行街连接西湖与商圈，边走边吃或看夜景都方便，步行至音乐喷泉约 10 分钟。",
    },
    "qinghefang": {
        "opening_hours": "街区全天开放；胡庆余堂中药博物馆 08:30–17:00。",
        "reservation_notice": "无需预约，胡庆余堂等场馆现场购票或预约。",
        "description": "清河坊与南宋御街相连，王星记扇庄、张小泉等老字号集中，适合边逛边了解南宋市井。",
    },
    "hangzhou-zoo": {
        "opening_hours": "07:00–17:30（16:30 停止入园）。",
        "reservation_notice": "可在官方渠道购票，节假日建议提前购票并按入园时段进园。",
        "description": "动物园依山而建，进门上坡较多，适合带孩子安排 2.5–3 小时，雨天园区路面湿滑。",
    },
    "hangzhou-wildlife-world": {
        "opening_hours": "09:00–17:00（16:00 停止入园）。",
        "reservation_notice": "需购票入园，自驾区与小火车另计，建议提前在官方渠道购票。",
        "description": "野生动物世界含车行区与步行区，亲子家庭通常安排一整天，自驾车可进入猛兽区。",
    },
    "hangzhou-paradise": {
        "opening_hours": "09:30–17:00，旺季周末延长至 17:30，夜场按官方场次开放。",
        "reservation_notice": "按票种分日场与夜场，节假日限流，建议提前购票。",
        "description": "杭州乐园以亲子游乐设施和演艺为主，一天只安排这一个项目比较从容，儿童身高限制现场会逐一核对。",
    },
    "qianjiang-city-balcony": {
        "opening_hours": "全天开放；城市灯光秀通常周末与节假日 19:00、20:00 各一场。",
        "reservation_notice": "无需预约，灯光秀场次以官方公告为准，江边风大注意保暖。",
        "description": "城市阳台视野开阔，可看钱塘江两岸天际线，适合夜间散步和城市夜景拍摄。",
    },
    "zhejiang-library-zhijiang": {
        "opening_hours": "周二至周日 09:00–17:00，周一闭馆。",
        "reservation_notice": "入馆需在官方小程序预约，周末座位紧张建议开馆前排队。",
        "description": "之江馆阅读空间宽敞，适合雨天安静看半天书，馆内与浙江省博物馆之江馆相邻。",
    },
    "china-national-silk-museum": {
        "opening_hours": "周二至周日 09:00–17:00（16:30 停止入馆），周一闭馆（法定节假日除外）。",
        "reservation_notice": "免费参观，需提前在官方渠道预约入馆名额。",
        "description": "丝绸博物馆从蚕桑到时装展厅完整，庭院适合拍照，看展约 1.5 小时。",
    },
}


# Places the demo catalogue actually sells that were missing from the pack.
KNOWLEDGE_ADDITIONS: tuple[dict[str, Any], ...] = (
    {
        "slug": "canal-night-cruise-gongchen",
        "name": "京杭大运河夜游（拱宸桥码头）",
        "category": "NIGHTLIFE",
        "area": "拱墅区拱宸桥",
        "address": "杭州市拱墅区桥弄街 1 号拱宸桥码头",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "COUPLE,FRIENDS,LOCAL_WEEKEND",
        "suggested_duration_minutes": 90,
        "opening_hours": "夜游航班通常在 18:30–21:00 之间发船，每班约 60–90 分钟。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "需提前订票并按班次在码头集合，开船前 15 分钟停止检票。",
        "description": "从拱宸桥码头上船沿运河看桥洞灯光与两岸夜景，全程约 1.5 小时，船上可远观桥西历史街区。",
        "source_name": "杭州市运河集团公开信息",
        "source_url": "https://www.hzcanal.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "mao-livehouse-hangzhou",
        "name": "杭州 MAO Livehouse",
        "category": "NIGHTLIFE",
        "area": "下城区",
        "address": "杭州市下城区屏风街 58 号",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "COUPLE,FRIENDS,SOLO",
        "minimum_age": 12,
        "suggested_duration_minutes": 120,
        "opening_hours": "演出通常 20:00 开场，散场约 22:00；无演出日晚间不开放。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "按演出场次购票，凭电子票入场，现场分站票与座位区。",
        "description": "小型现场音乐空间，乐队演出为主，结束后步行可达湖滨夜宵街区，适合朋友或情侣安排夜间行程。",
        "source_name": "MAO Livehouse 官方渠道",
        "source_url": "https://www.maolivehouse.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "hangzhou-childrens-theatre",
        "name": "杭州大剧院·儿童剧场",
        "category": "PERFORMANCE",
        "area": "上城区钱江新城",
        "address": "杭州市上城区之江路 1 号杭州大剧院",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "FAMILY",
        "minimum_age": 3,
        "maximum_age": 12,
        "suggested_duration_minutes": 90,
        "opening_hours": "周末与节假日常规 14:00、19:00 两场，单场约 75–90 分钟。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "按场次购票并对号入座，建议提前 30 分钟到场取票。",
        "description": "儿童剧以绘本改编与互动表演为主，适合 3–12 岁孩子，演出后可在钱江新城江边走走。",
        "source_name": "杭州大剧院官方渠道",
        "source_url": "https://www.hzgrandtheatre.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "low-carbon-science-museum",
        "name": "中国杭州低碳科技馆",
        "category": "SCIENCE_MUSEUM",
        "area": "滨江区",
        "address": "杭州市滨江区江汉路 1888 号",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "FAMILY,FRIENDS",
        "minimum_age": 4,
        "suggested_duration_minutes": 120,
        "opening_hours": "周三至周日 09:00–16:30，周一周二闭馆。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "免费参观，需提前预约，团队与周末场次名额有限。",
        "description": "以低碳与能源为主题的互动科技馆，儿童实验区可动手操作，是雨天亲子行程的常用备选。",
        "source_name": "中国杭州低碳科技馆官网",
        "source_url": "http://www.hzdtkjg.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "nanshan-pottery-space",
        "name": "南山陶艺空间",
        "category": "WORKSHOP",
        "area": "上城区南山路",
        "address": "杭州市上城区南山路 208 号",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "COUPLE,FRIENDS,FAMILY",
        "minimum_age": 6,
        "suggested_duration_minutes": 90,
        "opening_hours": "10:00–20:00，体验课按 10:30、14:00、16:30、19:00 分场。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "需按场次预约，作品烧制完成后 2–3 周可取或邮寄。",
        "description": "拉坯与手捏两种体验可选，老师逐桌指导，双人或亲子一起完成一件作品，成品可寄回家。",
        "source_name": "南山陶艺空间公开订课信息",
        "source_url": "https://www.dianping.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "qianjiang-karting",
        "name": "钱江卡丁车馆",
        "category": "SPORT",
        "area": "萧山区钱江世纪城",
        "address": "杭州市萧山区钱江世纪城体育中心",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "FRIENDS,COUPLE",
        "minimum_age": 12,
        "suggested_duration_minutes": 60,
        "opening_hours": "10:00–22:00，比赛场次每 15 分钟一轮。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "需提前预约场次，身高 1.4 米以上方可驾驶，现场签安全须知。",
        "description": "室内电动卡丁车，赛道短但节奏快，适合朋友或情侣连跑两轮，结束后可回酒店休息。",
        "source_name": "钱江卡丁车馆公开信息",
        "source_url": "https://www.dianping.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "hangzhou-climbing-gym",
        "name": "杭州室内攀岩馆",
        "category": "SPORT",
        "area": "西湖区",
        "address": "杭州市西湖区文二西路 808 号",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "FRIENDS,COUPLE,SOLO",
        "minimum_age": 8,
        "suggested_duration_minutes": 120,
        "opening_hours": "10:00–22:30，教学时段 14:00 与 19:00 各一场。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "首次体验含装备与教练，需提前预约并穿运动鞋。",
        "description": "抱石与顶绳两片区域，新手可跟教练体验两小时，是雨天也能安排的室内运动。",
        "source_name": "杭州室内攀岩馆公开信息",
        "source_url": "https://www.dianping.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "hubin-coffee-quarter",
        "name": "湖滨咖啡街区",
        "category": "FOOD",
        "area": "上城区湖滨",
        "address": "杭州市上城区平海路与湖滨路一带",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "SOLO,COUPLE,LOCAL_WEEKEND",
        "suggested_duration_minutes": 90,
        "opening_hours": "咖啡馆多在 08:00–22:00 营业，部分店 09:00 后开门。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "通常无需预约，周末 14:00–16:00 满座率较高。",
        "description": "湖滨一带咖啡馆密集，步行十五分钟内可串三四家，适合一个人慢慢喝或两人边逛边聊。",
        "source_name": "湖滨商圈公开信息",
        "source_url": "https://www.dianping.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "hubin-night-market",
        "name": "湖滨夜市与步行街",
        "category": "FOOD",
        "area": "上城区湖滨",
        "address": "杭州市上城区湖滨步行街",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "FRIENDS,COUPLE,LOCAL_WEEKEND",
        "suggested_duration_minutes": 120,
        "opening_hours": "夜市摊位通常 17:30 出摊，22:00 后陆续收摊。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "无需预约，热门小吃排队 10–20 分钟。",
        "description": "从湖滨步行街一路吃到龙翔桥，杭帮小吃与各地美食混在一起，适合作为晚间自由安排。",
        "source_name": "湖滨步行街公开信息",
        "source_url": "https://www.dianping.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "jiangnan-dessert-workshop",
        "name": "江南味觉体验馆",
        "category": "WORKSHOP",
        "area": "上城区",
        "address": "杭州市上城区中山中路 88 号",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS",
        "minimum_age": 5,
        "suggested_duration_minutes": 90,
        "opening_hours": "10:00–20:30，手作课按 11:00、15:00、18:30 分场。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "需提前预约课程，含材料与打包盒，成品当天带走。",
        "description": "桂花糕、定胜糕等江南甜品手作课，适合亲子和情侣一起做，做完可带回去当伴手礼。",
        "source_name": "江南味觉体验馆公开订课信息",
        "source_url": "https://www.dianping.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "deshougong-museum",
        "name": "南宋德寿宫遗址博物馆",
        "category": "MUSEUM",
        "area": "上城区",
        "address": "杭州市上城区望江路 218 号",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS,SOLO",
        "minimum_age": 5,
        "suggested_duration_minutes": 100,
        "opening_hours": "09:00–17:00（16:30 停止入场），周一闭馆。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "免费参观，需在官方渠道预约，数字展项按场次放行。",
        "description": "南宋皇家遗址与数字复原展示结合，红墙是热门拍照点，看展与拍照共约 1.5 小时。",
        "source_name": "南宋德寿宫遗址博物馆官方渠道",
        "source_url": "https://www.dsgmuseum.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "xianghu-lake",
        "name": "湘湖旅游度假区",
        "category": "NATURE",
        "area": "萧山区湘湖",
        "address": "杭州市萧山区湘湖路 132 号",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "FAMILY,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 120,
        "opening_hours": "景区全天开放，游船 08:30–17:00。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "开放式景区免费，游船与部分场馆现场购票。",
        "description": "湘湖人少水阔，环湖步道适合轻户外散步或骑行，秋天芦苇与杉林景色最好。",
        "source_name": "湘湖旅游度假区公开信息",
        "source_url": "https://www.xianghutour.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "liangzhu-ancient-city",
        "name": "良渚古城遗址公园",
        "category": "PARK",
        "area": "余杭区良渚",
        "address": "杭州市余杭区瓶窑镇凤都路 1 号",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS",
        "minimum_age": 4,
        "suggested_duration_minutes": 180,
        "opening_hours": "09:00–17:00（16:00 停止入园），周一闭园（法定节假日除外）。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "需购票并预约入园时段，园内观光车另计费用。",
        "description": "五千年前的古城遗址，观光车串起城墙、莫角山与反山王陵，亲子可搭配博物院一起安排半天以上。",
        "source_name": "良渚古城遗址公园官方渠道",
        "source_url": "https://www.liangzhupark.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "qiaoxi-historic-block",
        "name": "桥西历史文化街区",
        "category": "CITY_WALK",
        "area": "拱墅区拱宸桥",
        "address": "杭州市拱墅区桥西直街",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 90,
        "opening_hours": "街区全天开放，场馆与店铺多在 09:00–21:00。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "免费开放；工艺美术博物馆群需预约，手作体验课另行报名。",
        "description": "紧邻拱宸桥与运河，老仓库改成的博物馆与咖啡馆连成一片，傍晚沿河散步最舒服。",
        "source_name": "杭州市运河集团公开信息",
        "source_url": "https://www.hzcanal.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "nansong-imperial-street",
        "name": "南宋御街与中山中路",
        "category": "CITY_WALK",
        "area": "上城区",
        "address": "杭州市上城区中山中路",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,COUPLE,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 120,
        "opening_hours": "街区全天开放；沿街店铺通常 10:00–21:30。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "无需预约；胡庆余堂、方回春堂等场馆按各自开放时间参观。",
        "description": "南宋御街贯穿老城，从鼓楼走到西湖大道会经过老字号、药馆与咖啡馆，适合安排两小时慢逛。",
        "source_name": "杭州市上城区人民政府",
        "source_url": "https://www.hzsc.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "wansong-academy",
        "name": "万松书院",
        "category": "MUSEUM",
        "area": "上城区万松岭",
        "address": "杭州市上城区万松岭路 76 号",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,COUPLE,SOLO",
        "minimum_age": 6,
        "suggested_duration_minutes": 90,
        "opening_hours": "07:30–17:30（17:00 停止入园）。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "需购票入园，团队讲解需提前预约。",
        "description": "万松岭上的书院遗址，能看到古代书院格局与西湖远景，登高台阶较多，适合天气好的半天。",
        "source_name": "杭州西湖风景名胜区官方渠道",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "jiuxi-scenic",
        "name": "九溪烟树与九溪十八涧",
        "category": "NATURE",
        "area": "西湖区",
        "address": "杭州市西湖区九溪路",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS,SOLO",
        "suggested_duration_minutes": 150,
        "opening_hours": "全天开放，建议 08:00–16:30 之间徒步。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "免费开放；雨天溪石湿滑，不建议带幼儿深入。",
        "description": "溪流与茶园夹出的步行路线，从九溪路走到龙井村约 1.5 小时，夏天比市区凉快。",
        "source_name": "杭州西湖风景名胜区官方渠道",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "baita-park",
        "name": "白塔公园",
        "category": "NATURE",
        "area": "上城区",
        "address": "杭州市上城区老复兴街 1 号",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "FAMILY,COUPLE,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 90,
        "opening_hours": "全天开放；小火车 09:00–16:30。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "免费开放，小火车现场购票。",
        "description": "钱塘江畔的老铁路与白塔组合，江景开阔、人流少，适合带孩子和小火车拍照。",
        "source_name": "杭州市园林文物局公开信息",
        "source_url": "https://www.hzylwwj.hangzhou.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "daguan-road-block",
        "name": "大兜路历史街区",
        "category": "CITY_WALK",
        "area": "拱墅区",
        "address": "杭州市拱墅区大兜路",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "COUPLE,FRIENDS,LOCAL_WEEKEND",
        "suggested_duration_minutes": 90,
        "opening_hours": "街区全天开放，餐饮多在 11:00–22:00。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "无需预约；热门餐厅晚市建议提前订位。",
        "description": "运河边的餐饮街区，与香积寺、胜利河美食街相邻，适合把晚餐安排在运河夜游之前。",
        "source_name": "杭州市运河集团公开信息",
        "source_url": "https://www.hzcanal.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "tianmuli",
        "name": "天目里",
        "category": "ART_MUSEUM",
        "area": "西湖区",
        "address": "杭州市西湖区天目山路 398 号",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "COUPLE,FRIENDS,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 120,
        "opening_hours": "10:00–22:00；美术馆与书店通常 10:00–21:00。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "园区免费；美术馆展览需单独购票或预约。",
        "description": "建筑与书店、买手店、咖啡馆组成的街区，适合雨天看展、喝咖啡和拍照，停留两小时左右。",
        "source_name": "天目里官方渠道",
        "source_url": "https://ooev.ooev.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "zhijiang-museum",
        "name": "浙江省博物馆之江馆区",
        "category": "MUSEUM",
        "area": "西湖区之江",
        "address": "杭州市西湖区之江文化中心",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS,SOLO",
        "minimum_age": 6,
        "suggested_duration_minutes": 150,
        "opening_hours": "09:00–17:00（16:00 停止入馆），周一闭馆。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "免费参观，需提前预约；周末建议上午入馆。",
        "description": "之江文化中心的综合馆区，展陈面积大，适合与浙江图书馆之江馆、非遗馆一起安排半天。",
        "source_name": "浙江省博物馆官网",
        "source_url": "https://www.zhejiangmuseum.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "wulin-night-market",
        "name": "武林夜市",
        "category": "FOOD",
        "area": "拱墅区武林",
        "address": "杭州市拱墅区武林路与龙游路一带",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "FRIENDS,COUPLE,LOCAL_WEEKEND",
        "suggested_duration_minutes": 90,
        "opening_hours": "摊位通常 17:00 出摊，22:30 后陆续收摊。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "无需预约，晚市人流较大。",
        "description": "市中心的老夜市，小吃与手作摊位混在一起，适合住在附近酒店时当作晚间自由安排。",
        "source_name": "杭州市拱墅区公开信息",
        "source_url": "https://www.gongshu.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "olympic-sports-center",
        "name": "杭州奥体中心体育场（大莲花）",
        "category": "SPORT",
        "area": "滨江区",
        "address": "杭州市滨江区飞虹路",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FRIENDS,COUPLE,FAMILY",
        "suggested_duration_minutes": 90,
        "opening_hours": "外围公共区域全天开放；场馆内部仅赛事或开放日可进入。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "场馆参观需关注开放日安排，赛事按门票入场。",
        "description": "钱塘江畔的体育场馆建筑群，江边步道适合傍晚跑步或散步，夜景灯光也很出片。",
        "source_name": "杭州奥体中心公开信息",
        "source_url": "https://www.hzolympic.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "official-kiln-museum",
        "name": "杭州南宋官窑博物馆",
        "category": "MUSEUM",
        "area": "上城区玉皇山",
        "address": "杭州市上城区南复路 60 号",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "FAMILY,COUPLE,SOLO",
        "minimum_age": 5,
        "suggested_duration_minutes": 90,
        "opening_hours": "09:00–16:30（16:00 停止入场），周一闭馆。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "免费参观，需在官方渠道预约；陶艺体验课另行报名。",
        "description": "建在官窑遗址上的博物馆，可以看到龙窑与青瓷标本，还能报名简易陶艺体验，适合安排 1.5 小时。",
        "source_name": "杭州南宋官窑博物馆官方渠道",
        "source_url": "https://www.hzisk.org.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "huqingyutang-museum",
        "name": "胡庆余堂中药博物馆",
        "category": "MUSEUM",
        "area": "上城区河坊街",
        "address": "杭州市上城区大井巷 95 号",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "FAMILY,COUPLE,SOLO,LOCAL_WEEKEND",
        "minimum_age": 6,
        "suggested_duration_minutes": 60,
        "opening_hours": "08:30–17:00。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "需购票参观，节假日人流较大，建议上午前往。",
        "description": "晚清药号原址建筑与中药文化展陈，紧邻清河坊，逛完可顺路吃一顿杭帮菜，全程约 1 小时。",
        "source_name": "胡庆余堂官方渠道",
        "source_url": "https://www.hqyt.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "yunqi-bamboo-path",
        "name": "云栖竹径",
        "category": "NATURE",
        "area": "西湖区云栖",
        "address": "杭州市西湖区云栖坞",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "FAMILY,COUPLE,SOLO",
        "suggested_duration_minutes": 120,
        "opening_hours": "07:30–17:30。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "需购票入园，雨后竹径湿滑，建议穿防滑鞋。",
        "description": "竹林夹道的缓坡步道，夏天比市区低两三度，走完可以在五云山下喝茶，适合半日轻徒步。",
        "source_name": "杭州西湖风景名胜区官方渠道",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "baguadao-park",
        "name": "八卦田遗址公园",
        "category": "PARK",
        "area": "上城区玉皇山",
        "address": "杭州市上城区虎玉路",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "FAMILY,COUPLE,LOCAL_WEEKEND",
        "minimum_age": 3,
        "suggested_duration_minutes": 90,
        "opening_hours": "全天开放。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "免费开放，农事体验需现场咨询。",
        "description": "南宋皇家籍田遗址，八块田地按八卦排布，春季油菜花、秋季稻穗都很出片，适合亲子认识农作物。",
        "source_name": "杭州市园林文物局公开信息",
        "source_url": "https://www.hzylwwj.hangzhou.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "longjing-village",
        "name": "龙井村与十里琅珰",
        "category": "NATURE",
        "area": "西湖区龙井",
        "address": "杭州市西湖区龙井村",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS",
        "suggested_duration_minutes": 150,
        "opening_hours": "村内全天开放，茶农作息以清晨与午后为主。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "免费进入；茶园拍照需征得茶农同意，采茶体验按季节另行预约。",
        "description": "从龙井村沿十里琅珰走到五云山或梅家坞，一路茶园与山脊视野，适合安排 2.5 小时轻徒步。",
        "source_name": "杭州西湖风景名胜区官方渠道",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "tangqi-ancient-town",
        "name": "塘栖古镇",
        "category": "CITY_WALK",
        "area": "临平区塘栖",
        "address": "杭州市临平区塘栖镇",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,COUPLE,LOCAL_WEEKEND",
        "suggested_duration_minutes": 180,
        "opening_hours": "古镇全天开放，店铺多在 09:00–20:00。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "古镇免费，广济桥与部分展馆免费开放；从市区驾车约 40 分钟。",
        "description": "京杭大运河上的七孔石桥与临水老街，枇杷季（5 月）最热闹，适合安排半天并吃一顿细沙羊尾。",
        "source_name": "杭州市临平区公开信息",
        "source_url": "https://www.linping.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "tea-museum-longjing",
        "name": "中国茶叶博物馆龙井馆区",
        "category": "MUSEUM",
        "area": "西湖区龙井",
        "address": "杭州市西湖区翁家山 268 号",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,COUPLE,SOLO",
        "suggested_duration_minutes": 90,
        "opening_hours": "09:00–17:00（16:30 停止入场），周一闭馆。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "免费参观，茶文化课程需提前报名。",
        "description": "龙井馆区建在茶山之间，展厅讲茶叶贸易与制茶工艺，出馆就能走进茶园，适合与龙井村串成半日行程。",
        "source_name": "中国茶叶博物馆官方渠道",
        "source_url": "https://www.teamuseum.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "baoshi-hill",
        "name": "宝石山与初阳台",
        "category": "NATURE",
        "area": "西湖区北山街",
        "address": "杭州市西湖区宝石山",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "COUPLE,FRIENDS,SOLO",
        "suggested_duration_minutes": 120,
        "opening_hours": "全天开放，建议日落前 1.5 小时上山。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "免费开放，山路石阶较多，雨天湿滑不建议带幼儿。",
        "description": "登顶约 30 分钟，可在初阳台俯瞰西湖全景，是看日落与城市夜景的经典机位，下山即是北山街。",
        "source_name": "杭州西湖风景名胜区官方渠道",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "hangzhou-library",
        "name": "杭州图书馆（市民中心馆）",
        "category": "LIBRARY",
        "area": "上城区钱江新城",
        "address": "杭州市上城区解放东路 58 号",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "SOLO,COUPLE,FAMILY",
        "suggested_duration_minutes": 120,
        "opening_hours": "周二至周日 09:00–21:00，周一闭馆。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "免费入馆，周末座位紧张，建议开馆后前往。",
        "description": "钱江新城的花园式图书馆，落地窗与阅读区适合雨天安静待一下午，旁边就是城市阳台。",
        "source_name": "杭州图书馆官方渠道",
        "source_url": "https://www.hzlib.net/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "xixi-longshe",
        "name": "西溪湿地洪园（龙舌嘴）",
        "category": "NATURE",
        "area": "余杭区五常",
        "address": "杭州市余杭区五常大道 2 号",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS",
        "suggested_duration_minutes": 150,
        "opening_hours": "08:00–17:30（16:30 停止入园）。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "需购票入园，摇橹船另计，建议提前线上购票。",
        "description": "洪园人少水阔，摇橹船穿过芦苇与柿林，秋季有火柿节，适合亲子半日慢游。",
        "source_name": "西溪湿地官方渠道",
        "source_url": "https://www.xixiwetland.com.cn/",
        "verification_status": "ACTIVE",
    },
)


# 第二批扩充：补齐西湖沿线经典景点、运河与良渚的收尾场馆，以及游客常问的
# 亲子/夜游/茶村细节。字段口径与上面的记录一致：写成「官方一般规则 + 需以当天
# 公告为准」的可核对事实，方便工作台按来源页再核验。
KNOWLEDGE_EXPANSION: tuple[dict[str, Any], ...] = (
    {
        "slug": "leifeng-pagoda",
        "name": "雷峰塔景区",
        "category": "CITY_WALK",
        "area": "西湖区西湖南岸",
        "address": "杭州市西湖区南山路 15 号",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 60,
        "opening_hours": "旺季约 08:00–20:00，淡季约 08:00–17:30（以景区当日公告为准）。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "需购票登塔，塔内为电梯与步行并存，节假日晚间客流集中请提前购票。",
        "description": "登塔可俯瞰西湖全景与南屏山，塔内底层保留雷峰塔遗址与白蛇传主题陈列；傍晚上塔看完日落再走南山路最顺。",
        "source_name": "杭州西湖风景名胜区公开信息",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "three-pools-mirror-moon",
        "name": "三潭印月·小瀛洲",
        "category": "CITY_WALK",
        "area": "西湖区西湖湖心",
        "address": "杭州市西湖区西湖小瀛洲岛",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS,SOLO",
        "suggested_duration_minutes": 90,
        "opening_hours": "随游船班次开放，通常 08:00–16:30 之间上岛，末班船时间以码头当日公示为准。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "需乘船前往，船票含登岛；旺季建议在湖滨或花港码头提前购票并留出行船时间。",
        "description": "小瀛洲是湖心园林岛，九曲桥串起开网亭与三潭印月主景，岛上看西湖的角度和岸边完全不同，适合半天慢慢走。",
        "source_name": "杭州西湖风景名胜区公开信息",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "lingyin-temple",
        "name": "灵隐寺·飞来峰",
        "category": "CITY_WALK",
        "area": "西湖区灵隐",
        "address": "杭州市西湖区法云弄 1 号",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS,SOLO",
        "suggested_duration_minutes": 150,
        "opening_hours": "飞来峰景区约 06:30–18:00，灵隐寺约 07:00–17:30（以当日公告为准）。",
        "weather_adaptations": "CLOUDY,SUNNY,RAIN",
        "reservation_notice": "需分别购买飞来峰景区门票与灵隐寺香花券，周末与初一十五客流大，建议早上开园即入。",
        "description": "先看飞来峰造像群与冷泉溪，再入灵隐寺礼佛；出寺可沿法云弄步行到永福寺、韬光寺，午后能一路走到北高峰索道。",
        "source_name": "灵隐寺官方渠道",
        "source_url": "https://www.lingyinsi.org/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "yuewang-temple",
        "name": "岳王庙",
        "category": "MUSEUM",
        "area": "西湖区北山街",
        "address": "杭州市西湖区北山街 80 号",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,SOLO,COUPLE",
        "minimum_age": 6,
        "suggested_duration_minutes": 60,
        "opening_hours": "约 07:30–17:30（以景区当日公告为准）。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "需购票入内，讲解场次以现场公告为准。",
        "description": "岳飞墓与忠烈祠坐落于栖霞岭南麓，墓园、碑刻与壁画串起南宋历史，出门就是曲院风荷与苏堤北口，适合与北山街一起排半天。",
        "source_name": "杭州西湖风景名胜区公开信息",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "six-harmony-pagoda",
        "name": "六和塔文化公园",
        "category": "CITY_WALK",
        "area": "西湖区之江路",
        "address": "杭州市西湖区之江路 16 号",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,COUPLE,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 75,
        "opening_hours": "约 06:30–17:30（以景区当日公告为准）。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "登塔需购票，塔内台阶较窄，雨天注意湿滑。",
        "description": "六和塔临钱塘江而立，登塔可望钱塘江大桥与之江两岸；塔下公园安静，适合与九溪、白塔公园串成之江半日线。",
        "source_name": "杭州西湖风景名胜区公开信息",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "manjuelong-osmanthus",
        "name": "满觉陇·满陇桂雨公园",
        "category": "NATURE",
        "area": "西湖区满觉陇",
        "address": "杭州市西湖区满觉陇路",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "COUPLE,FRIENDS,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 90,
        "opening_hours": "开放式山径，全天可走；公园收费区约 08:30–17:00。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "桂花季（多为 9 月下旬至 10 月中旬）人流集中，建议上午前往并预约附近茶室。",
        "description": "从石屋洞沿满觉陇路上行，两侧是茶山与桂花林，桂花季一路桂香；村里有茶室可坐下喝一杯明前龙井，走到水乐洞再折返约 1.5 小时。",
        "source_name": "杭州西湖风景名胜区公开信息",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "hupao-spring",
        "name": "虎跑公园·虎跑梦泉",
        "category": "NATURE",
        "area": "西湖区虎跑路",
        "address": "杭州市西湖区虎跑路 39 号",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "FAMILY,COUPLE,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 75,
        "opening_hours": "约 06:30–18:00（以景区当日公告为准）。",
        "weather_adaptations": "CLOUDY,SUNNY,RAIN",
        "reservation_notice": "需购票入园，取泉水点可自带容器，周末茶室需等位。",
        "description": "虎跑泉与龙井茶是杭州经典的「双绝」，园内竹林溪涧适合慢走；入园后可到李叔同纪念馆与济公塔院看一圈。",
        "source_name": "杭州西湖风景名胜区公开信息",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "jingci-temple",
        "name": "净慈寺",
        "category": "CITY_WALK",
        "area": "西湖区南屏山",
        "address": "杭州市西湖区南山路 56 号",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "SOLO,COUPLE,FAMILY,LOCAL_WEEKEND",
        "suggested_duration_minutes": 60,
        "opening_hours": "约 06:30–17:00（以寺院当日公告为准）。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "需购香花券入寺，晚间南屏晚钟活动按寺院公告开放。",
        "description": "净慈寺在南屏山下，与雷峰塔隔路相望，寺内运木古井与钟楼是「南屏晚钟」的由来，傍晚在寺前广场听钟声收尾很安静。",
        "source_name": "净慈寺官方渠道",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "wushan-chenghuang-pavilion",
        "name": "吴山城隍阁",
        "category": "CITY_WALK",
        "area": "上城区吴山",
        "address": "杭州市上城区吴山路 3 号",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 90,
        "opening_hours": "约 07:30–22:00（以景区当日公告为准），登阁约至 21:30。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "登阁需购票，傍晚上山看西湖与城景的人多，建议留出排队时间。",
        "description": "从河坊街或吴山广场上山，登城隍阁可俯瞰西湖、运河与城市天际线；山上茶座多，适合傍晚看夜景后再沿大马弄下山吃夜宵。",
        "source_name": "杭州市文化广电旅游局公开信息",
        "source_url": "https://wglyj.hangzhou.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "xiaoshan-cross-lake-bridge-museum",
        "name": "跨湖桥遗址博物馆",
        "category": "MUSEUM",
        "area": "萧山区湘湖",
        "address": "杭州市萧山区湘湖路 978 号",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "FAMILY,SOLO,COUPLE",
        "minimum_age": 5,
        "suggested_duration_minutes": 90,
        "opening_hours": "09:00–17:00（16:00 停止入场），周一闭馆，法定节假日照常开放。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "免费参观，需在官方渠道预约；馆内独木舟遗址为主展项。",
        "description": "跨湖桥遗址出土的独木舟把浙江史前史往前推了一大截，展馆临湘湖，看完可沿湖骑行或走到下孙文化村，半天刚好。",
        "source_name": "跨湖桥遗址博物馆公开信息",
        "source_url": "https://www.xianghutrip.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "hangzhou-confucian-temple",
        "name": "杭州孔庙·碑林",
        "category": "MUSEUM",
        "area": "上城区劳动路",
        "address": "杭州市上城区府学巷 8 号",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,SOLO,COUPLE,LOCAL_WEEKEND",
        "minimum_age": 5,
        "suggested_duration_minutes": 60,
        "opening_hours": "09:00–16:30，周一闭馆（以场馆公告为准）。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "免费参观，团队讲解需提前预约。",
        "description": "孔庙大成殿与石经阁碑林连成一体，院中石经与拓片适合带孩子认字看碑；出了门就是劳动路，离西湖天地和吴山都很近。",
        "source_name": "杭州市园林文物局公开信息",
        "source_url": "https://wglyj.hangzhou.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "jingshan-temple",
        "name": "径山寺",
        "category": "CITY_WALK",
        "area": "余杭区径山",
        "address": "杭州市余杭区径山镇长径线",
        "indoor_outdoor": "MIXED",
        "suitable_crowds": "FAMILY,COUPLE,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 180,
        "opening_hours": "约 07:00–17:00（以寺院当日公告为准），索道约 08:00–16:30。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "山门至寺院可步行或乘接驳/索道，节假日车位紧张，建议早到。",
        "description": "径山是日本茶道的重要源头，寺院隐在竹山之间，寺内可体验径山茶宴与素斋；上山步道穿过茶园，适合安排一整天的郊区行程。",
        "source_name": "径山寺官方渠道",
        "source_url": "https://www.jingshansi.org/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "zhejiang-museum-zhijiang-hall",
        "name": "浙江省博物馆之江馆区",
        "category": "MUSEUM",
        "area": "西湖区之江",
        "address": "杭州市西湖区之江文化中心",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "FAMILY,SOLO,COUPLE,LOCAL_WEEKEND",
        "minimum_age": 6,
        "suggested_duration_minutes": 150,
        "opening_hours": "09:00–17:00（16:00 停止入场），周一闭馆，法定节假日照常开放。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "免费参观，需在官方渠道预约；周末讲解场次需提前约。",
        "description": "之江馆区以浙江历史与书画大展为主，展厅大、互动多，和之江文化中心的图书馆、非遗馆连在一起，雨天可以待一整天。",
        "source_name": "浙江省博物馆官方渠道",
        "source_url": "https://www.zhejiangmuseum.com/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "meijiawu-tea-village",
        "name": "梅家坞茶文化村",
        "category": "WORKSHOP",
        "area": "西湖区梅家坞",
        "address": "杭州市西湖区梅灵南路梅家坞",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 120,
        "opening_hours": "茶村全天开放，各家茶室多为 09:00–18:00。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "采茶、炒茶体验与茶餐按茶室安排，旺季周末建议提前一天预订。",
        "description": "梅家坞在西湖群山间，沿梅灵南路是连片茶园；可以跟茶农进园采茶、看手工炒制，再坐下喝一泡当年龙井，中午在村里吃茶香鸡与笋干。",
        "source_name": "杭州西湖风景名胜区公开信息",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "baochu-pagoda",
        "name": "保俶塔·宝石山",
        "category": "CITY_WALK",
        "area": "西湖区宝石山",
        "address": "杭州市西湖区北山街宝石山",
        "indoor_outdoor": "OUTDOOR",
        "suitable_crowds": "COUPLE,FRIENDS,SOLO,LOCAL_WEEKEND",
        "suggested_duration_minutes": 90,
        "opening_hours": "山径全天开放，傍晚人多，夜间建议结伴并注意照明。",
        "weather_adaptations": "CLOUDY,SUNNY",
        "reservation_notice": "无需预约，登山步道石阶较多，建议穿防滑鞋。",
        "description": "从北山街小路上宝石山，可到初阳台与蛤蟆峰看西湖全景，保俶塔就在山脊上；傍晚上山看日落再沿葛岭下山，是本地人常走的看湖路线。",
        "source_name": "杭州西湖风景名胜区公开信息",
        "source_url": "https://www.hzwestlake.gov.cn/",
        "verification_status": "ACTIVE",
    },
    {
        "slug": "hangzhou-dajuyuan-shangcheng",
        "name": "杭州大剧院",
        "category": "PERFORMANCE",
        "area": "上城区钱江新城",
        "address": "杭州市上城区之江路 1 号",
        "indoor_outdoor": "INDOOR",
        "suitable_crowds": "FAMILY,COUPLE,FRIENDS,SOLO",
        "suggested_duration_minutes": 120,
        "opening_hours": "按演出场次开放，通常 19:30 开演；白天大堂可进。",
        "weather_adaptations": "RAIN,CLOUDY,SUNNY",
        "reservation_notice": "需按场次购票对号入座，建议提前 30 分钟到场取票、存包。",
        "description": "杭州大剧院以音乐厅与歌剧院为主的演出场馆，临钱塘江与城市阳台；看晚场演出前后可以沿江边散步看钱江新城的灯光。",
        "source_name": "杭州大剧院官方渠道",
        "source_url": "https://www.hzgrandtheatre.com/",
        "verification_status": "ACTIVE",
    },
)
