<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { showToast } from 'vant'
import { visitorApi } from '../../api'
import { errorMessage } from '../../api/client'
import StatusTag from '../../components/StatusTag.vue'
import type { TravelProduct } from '../../types'

const route = useRoute(); const product = ref<TravelProduct | null>(null); const loading = ref(true); const question = ref(''); const chats = ref<Array<{ user?: string; answer?: string }>>([]); const consultLoading = ref(false); const intentDialog = ref(false); const intentLoading = ref(false)
const form = reactive({ adult_count: 2, child_count: 1, child_ages: '6', budget: '700', interests: '手工', allergy_information: '', contact_name: '', contact_phone: '' })
async function load() { try { product.value = (await visitorApi.product(Number(route.params.id))).data } catch (e) { showToast(errorMessage(e)) } finally { loading.value = false } }
async function consult() { if (!question.value.trim()) return; const text = question.value; question.value = ''; chats.value.push({ user: text }); consultLoading.value = true; try { const response = await visitorApi.consult({ product_id: product.value?.id, question: text, weather: product.value?.weather || 'RAIN', child_age: Number(form.child_ages) || undefined }); chats.value.push({ answer: String(response.data.answer || '') }) } catch (e) { showToast(errorMessage(e)) } finally { consultLoading.value = false } }
async function submitIntent() { if (!product.value) return; intentLoading.value = true; try { await visitorApi.intent({ product_id: product.value.id, adult_count: form.adult_count, child_count: form.child_count, child_ages: form.child_count ? form.child_ages.split(/[,，]/).filter(Boolean).map(Number) : [], budget: form.budget, interests: form.interests.split(/[,，]/).filter(Boolean), allergy_information: form.allergy_information, contact_name: form.contact_name, contact_phone: form.contact_phone }); showToast('预约意向已提交'); intentDialog.value = false } catch (e) { showToast(errorMessage(e)) } finally { intentLoading.value = false } }
onMounted(load)
</script>

<template>
  <div v-if="loading" class="panel empty-state">正在读取套餐详情…</div>
  <div v-else-if="product">
    <div class="detail-hero"><div class="eyebrow">{{ product.theme }} · {{ product.target_date }} · {{ product.weather }}</div><h1>{{ product.product_name }}</h1><h3>{{ product.marketing_title }}</h3><p class="muted">{{ product.marketing_content }}</p><div class="detail-hero__bottom"><div><span class="price-large">¥{{ product.suggested_price }}</span><span class="muted"> /套 · 含房间、酒店服务与文化体验</span></div><div><StatusTag :status="product.status" /><span :class="product.sale_quantity <= 2 ? 'warning-text' : 'muted'" style="margin-left:10px">仅余 {{ product.sale_quantity }} 套</span></div></div></div>
    <div class="detail-grid"><div>
      <div class="panel"><div class="section-title" style="margin-top:0"><h2>套餐包含</h2><span>真实资源与实时场次</span></div><div v-for="item in product.resources" :key="item.id" class="visitor-resource-row"><div><strong>{{ item.resource_name }}</strong><div class="muted">{{ item.resource_type }} · {{ item.available_date || product.target_date }} · {{ item.address || '酒店内或商户场地' }}</div></div><span>× {{ item.quantity_per_package }}</span></div></div>
      <div class="panel" style="margin-top:18px"><div class="section-title" style="margin-top:0"><h2>时间安排</h2><span>场次以实时确认结果为准</span></div><div class="chat-list"><div class="chat-bubble"><strong>15:00 · 办理入住</strong><br><span class="muted">入住后领取文化体验时间卡</span></div><div v-for="item in product.resources" :key="`time-${item.id}`" class="chat-bubble"><strong>{{ item.start_time?.slice(0,5) || '待确认' }} · {{ item.resource_name }}</strong><br><span class="muted">{{ item.start_time && item.end_time ? `${item.start_time.slice(0,5)}-${item.end_time.slice(0,5)}` : '商户实时确认场次' }} · 每套使用 {{ item.quantity_per_package }} 份</span></div></div></div>
      <div v-if="product.marketing_assets?.length" class="panel marketing-preview" style="margin-top:18px"><div class="section-title" style="margin-top:0"><h2>杭州旅行灵感</h2><span>智能生成营销素材</span></div><div v-for="asset in product.marketing_assets.filter(item => item.asset_type !== 'POSTER')" :key="asset.asset_type" class="inspiration"><strong>{{ asset.title }}</strong><p class="muted">{{ asset.content }}</p></div></div>
      <div class="panel" style="margin-top:18px"><div class="section-title" style="margin-top:0"><h2>智能咨询</h2><span>AI解释 · 规则兜底</span></div><div class="chat-list"><div v-for="(chat,index) in chats" :key="index" :class="['chat-bubble', chat.user ? 'user' : '']">{{ chat.user || chat.answer }}</div><div v-if="consultLoading" class="chat-bubble">正在根据当前套餐约束回答…</div></div><div style="display:flex;gap:8px"><el-input v-model="question" placeholder="例如：雨天可以参加吗？" @keyup.enter="consult" /><el-button type="primary" @click="consult">发送</el-button></div></div>
    </div><div><div class="panel sticky-panel"><div class="section-title" style="margin-top:0"><h2>预约意向</h2></div><p class="muted" style="line-height:1.7">比赛版本不收款。提交后酒店会根据房量、名额和过敏信息联系确认。</p><el-button type="primary" size="large" style="width:100%" @click="intentDialog=true">提交预约意向</el-button><div class="panel" style="box-shadow:none;background:#fff8eb;margin-top:16px"><strong>风险提示</strong><p class="danger-text" style="font-size:12px;line-height:1.7">{{ product.risk_message }}</p></div></div></div></div>
    <el-dialog v-model="intentDialog" title="填写预约意向" width="450px"><el-form label-position="top"><div class="form-grid"><el-form-item label="成人数"><el-input-number v-model="form.adult_count" :min="1" /></el-form-item><el-form-item label="儿童数"><el-input-number v-model="form.child_count" :min="0" /></el-form-item><el-form-item label="儿童年龄"><el-input v-model="form.child_ages" placeholder="多个年龄用逗号分隔" /></el-form-item><el-form-item label="预算上限"><el-input v-model="form.budget" /></el-form-item><el-form-item label="兴趣"><el-input v-model="form.interests" /></el-form-item><el-form-item label="联系人"><el-input v-model="form.contact_name" /></el-form-item><el-form-item label="联系电话"><el-input v-model="form.contact_phone" /></el-form-item><el-form-item class="full" label="饮食禁忌 / 过敏信息"><el-input v-model="form.allergy_information" type="textarea" placeholder="请填写，酒店与商户会在确认前再次核对" /></el-form-item></div></el-form><template #footer><el-button @click="intentDialog=false">取消</el-button><el-button type="primary" :loading="intentLoading" @click="submitIntent">提交意向</el-button></template></el-dialog>
  </div>
  <div v-else class="panel empty-state">套餐不存在或已下架</div>
</template>

<style scoped>
.detail-hero__bottom{display:flex;align-items:end;justify-content:space-between;margin-top:24px;gap:12px}.visitor-resource-row{display:flex;justify-content:space-between;align-items:center;padding:14px 0;border-top:1px solid var(--line)}.marketing-preview{background:linear-gradient(135deg,#f6fbf8,#fffaf0)}.inspiration{padding:10px 0;border-top:1px solid var(--line)}.inspiration p{line-height:1.7;margin:6px 0}@media(max-width:600px){.detail-hero__bottom{display:block}.detail-hero__bottom>div:last-child{margin-top:15px}}
</style>
