<script setup lang="ts">
import { reactive, ref } from 'vue'
import { showToast } from 'vant'
import { visitorApi } from '../../api'
import { errorMessage } from '../../api/client'
import ProductCard from '../../components/ProductCard.vue'
import type { Recommendation } from '../../types'

const loading = ref(false); const results = ref<Recommendation[]>([]); const interpreted = ref<Record<string, unknown> | null>(null)
const form = reactive({ natural_language: '我们一家三口带一个6岁孩子，预算700元，明天下雨，想住亲子房，喜欢手工和非遗，下午四点左右体验，孩子有花生过敏。', target_date: '', weather: 'RAIN', adult_count: 2, child_count: 1, child_ages: '6', budget: '700', interests: '手工,非遗', dietary_restrictions: '', allergy_information: '花生过敏', arrival_time: '15:00', preferred_experience_time: '16:00', other_requirements: '' })
async function submit() {
  if (!form.natural_language.trim()) { showToast('请先描述你的旅行需求'); return }
  loading.value = true
  try {
    const response = await visitorApi.recommend({ natural_language: form.natural_language, target_date: form.target_date || undefined, weather: form.weather, adult_count: form.adult_count, child_count: form.child_count, child_ages: form.child_count ? form.child_ages.split(/[,，]/).filter(Boolean).map(Number) : [], budget: form.budget, interests: form.interests.split(/[,，]/).filter(Boolean), dietary_restrictions: form.dietary_restrictions.split(/[,，]/).filter(Boolean), allergy_information: form.allergy_information, arrival_time: form.arrival_time || undefined, preferred_experience_time: form.preferred_experience_time || undefined, other_requirements: form.other_requirements })
    results.value = response.data.results; interpreted.value = response.data.interpreted_needs || null
    if (!results.value.length) showToast('当前没有完全满足库存、天气、年龄和预算约束的套餐'); else showToast(`已根据自然语言找到 ${results.value.length} 个推荐`)
  } catch (e) { showToast(errorMessage(e)) } finally { loading.value = false }
}
</script>

<template>
  <div class="page-head"><div><div class="eyebrow">NATURAL LANGUAGE TRAVEL MATCHING</div><h1>用一句话规划杭州旅居</h1><p>支持自然语言描述人数、预算、天气、兴趣、时间、饮食禁忌和过敏信息；系统先做库存与安全规则筛选，再用 Skill 生成推荐理由和时间安排。</p></div></div>
  <div class="split-layout">
    <div class="panel sticky-panel"><div class="section-title" style="margin-top:0"><h2>告诉我你的需求</h2><span>无需注册</span></div><el-form label-position="top"><el-form-item label="自然语言需求" class="full"><el-input v-model="form.natural_language" type="textarea" :rows="6" maxlength="1000" show-word-limit placeholder="例如：两位大人带一个6岁孩子，预算700元，明天下雨，喜欢非遗手工，下午四点体验，不吃辣且花生过敏。" /></el-form-item><div class="quick-prompts"><button @click="form.natural_language='两位大人带两个孩子，预算1000元，周末晴天，想要茶文化和旅拍。'">亲子晴日</button><button @click="form.natural_language='情侣两人预算800元，雨天想要安静的茶文化体验和美食。'">情侣雨天</button><button @click="form.natural_language='本地周末微度假，预算600元，喜欢博物馆和慢游，下午出发。'">本地慢游</button></div><div class="advanced-toggle"><span>结构化约束（可选，用于精确校验）</span></div><div class="form-grid"><el-form-item label="入住日期"><el-date-picker v-model="form.target_date" type="date" value-format="YYYY-MM-DD" style="width:100%" placeholder="不指定" /></el-form-item><el-form-item label="天气"><el-select v-model="form.weather" style="width:100%"><el-option label="小雨" value="RAIN" /><el-option label="晴天" value="SUNNY" /><el-option label="多云" value="CLOUDY" /></el-select></el-form-item><el-form-item label="成人"><el-input-number v-model="form.adult_count" :min="1" style="width:100%" /></el-form-item><el-form-item label="儿童"><el-input-number v-model="form.child_count" :min="0" style="width:100%" /></el-form-item><el-form-item class="full" label="儿童年龄"><el-input v-model="form.child_ages" placeholder="例如 6,9" /></el-form-item><el-form-item label="预算上限"><el-input v-model="form.budget"><template #prepend>¥</template></el-input></el-form-item><el-form-item label="兴趣关键词"><el-input v-model="form.interests" placeholder="手工,茶文化" /></el-form-item><el-form-item class="full" label="饮食禁忌"><el-input v-model="form.dietary_restrictions" placeholder="不吃辣,素食" /></el-form-item><el-form-item class="full" label="过敏信息"><el-input v-model="form.allergy_information" type="textarea" :rows="2" placeholder="例如：花生过敏" /></el-form-item><el-form-item label="预计到店"><el-time-select v-model="form.arrival_time" start="08:00" step="00:30" end="22:00" style="width:100%" /></el-form-item><el-form-item label="期望体验时间"><el-time-select v-model="form.preferred_experience_time" start="08:00" step="00:30" end="22:00" style="width:100%" /></el-form-item><el-form-item class="full" label="其他要求"><el-input v-model="form.other_requirements" placeholder="例如：希望安排轻松、不赶行程" /></el-form-item></div><el-button type="primary" size="large" :loading="loading" style="width:100%" @click="submit">✦ 智能解析并推荐套餐</el-button></el-form></div>
    <div>
      <div v-if="interpreted" class="panel interpreted-card"><div class="section-title" style="margin-top:0"><h2>已理解的需求</h2><span>可解释匹配</span></div><div class="interpreted-chips"><span>天气：{{ interpreted.weather }}</span><span>预算：¥{{ interpreted.budget }}</span><span>同行：{{ interpreted.adult_count }} 成人 + {{ interpreted.child_count }} 儿童</span><span v-if="(interpreted.child_ages as number[])?.length">年龄：{{ (interpreted.child_ages as number[]).join('、') }} 岁</span><span v-for="item in (interpreted.interests as string[]) || []" :key="item">兴趣：{{ item }}</span><span v-if="interpreted.allergy_information">安全提示：{{ interpreted.allergy_information }}</span></div></div>
      <div v-if="!results.length && !loading" class="panel empty-state"><div><div style="font-size:36px;color:#b8d8ce">♡</div><p>先用一句话描述你的旅行，系统会返回适合当前真实库存的套餐。</p></div></div><div v-if="loading" class="panel empty-state">正在理解自然语言，并匹配房量、天气、年龄、时段、预算与过敏风险…</div>
      <div v-for="item in results" :key="item.product.id" class="panel recommendation-panel"><div class="product-card__top"><span class="eyebrow">匹配分 {{ item.score }}</span><span class="muted">{{ item.product.sale_quantity }} 套可售 · ¥{{ item.product.suggested_price }}</span></div><ProductCard :product="item.product" public-view /><p class="recommendation-reason">{{ item.recommendation_reason }}</p><div class="product-card__resources"><span :class="item.budget_match ? '' : 'warning-text'">预算 {{ item.budget_match ? '匹配' : '超出' }}</span><span>儿童 {{ item.children_match ? '适配' : '需确认' }}</span><span>天气 {{ item.weather_match ? '适配' : '不适配' }}</span><span>兴趣 {{ item.interest_match ? '命中' : '可替换' }}</span></div><div v-if="item.schedule.length" class="panel schedule-panel"><strong>住宿 · 餐饮 · 文化体验安排</strong><p v-for="event in item.schedule" :key="event.time + event.title" class="muted" style="line-height:1.5;margin:8px 0"><b>{{ event.time }}</b> · {{ event.title }}：{{ event.description }}</p></div><div v-if="item.limited_adjustments.length" class="adjustment-hints"><strong>可做的有限调整</strong><span v-for="hint in item.limited_adjustments" :key="hint">{{ hint }}</span></div><div v-if="item.allergy_warning" class="danger-text allergy-note">{{ item.allergy_warning }}</div><div style="text-align:right;margin-top:12px"><el-button type="primary" plain @click="$router.push(`/visitor/products/${item.product.id}`)">查看套餐并预约</el-button></div></div>
    </div>
  </div>
</template>

<style scoped>
.quick-prompts{display:flex;flex-wrap:wrap;gap:6px;margin:-4px 0 16px}.quick-prompts button{border:1px solid #cfe6dc;background:#f2faf6;color:var(--teal);border-radius:999px;padding:6px 9px;font-size:11px}.advanced-toggle{border-top:1px solid var(--line);padding:15px 0 10px;color:var(--muted);font-size:12px}.interpreted-card{margin-bottom:14px;background:linear-gradient(135deg,#f0faf5,#fffaf0)}.interpreted-chips{display:flex;flex-wrap:wrap;gap:8px}.interpreted-chips span,.adjustment-hints span{background:#fff;border:1px solid #dcece5;border-radius:999px;padding:6px 9px;font-size:11px;color:var(--teal-dark)}.recommendation-panel{margin-bottom:14px}.recommendation-reason{font-size:14px;line-height:1.8;margin:4px 0}.schedule-panel{box-shadow:none;background:#f8fbf9;margin-top:12px}.adjustment-hints{display:flex;flex-wrap:wrap;align-items:center;gap:7px;margin-top:12px}.adjustment-hints strong{font-size:12px}.allergy-note{font-size:12px;line-height:1.7;margin-top:12px}
</style>
